Resources:
  # Define the IAM Policy
  CloudFormationIAMECRPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "CloudFormationIAMPolicyECR"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:DescribeRepositories"
              - "ecr:ListImages"
              - "ecr:DescribeImages"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:PutImage"
            Resource: "*"


  # Reference the existing IAM user
  ExistingUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "Janice"

    # Attach the policy to the user
  AttachPolicyToUser:
    Type: "AWS::IAM::UserToGroupAddition"
    Properties:
      GroupName: !Ref ExistingUser
      Users:
        - !Ref CloudFormationIAMECRPolicy
