Resources:
  # Define the IAM Policy
  MyPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "MyCustomPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:DescribeRepositories"
              - "ecr:ListImages"
              - "ecr:DescribeImages"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:PutImage"
            Resource: "*"
      Users:
        - Ref: ExistingUser

  # Reference the existing IAM user
  ExistingUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "Janice"
