name: Test an endpoint

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test an endpoint
      run: |
        curl http://0.0.0.0:8000/ping
